---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: freenas-nfs-provisioner
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: freenas-nfs-provisioner
    spec:
      serviceAccountName: freenas-nfs-provisioner
      containers:
        - name: freenas-nfs-provisioner
          image: docker.io/nmaupu/freenas-provisioner:2.3
          env:
            #- name: IDENTIFIER
            #  value:
            #- name: PROVISIONER_NAME
            #  value:
